apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  namespace: quay
  name: quayecosystem
spec:
  clair:
    enabled: true
    updateInterval: 60m
    database:
      volumeSize: 10Gi
    imagePullSecretName: redhat-pull-secret
  quay:
    keepConfigDeployment: true
    externalAccess:
      configHostname: quay-config.apps.name.dev-oops.tech
      hostname: quay.apps.name.dev-oops.tech
      tls:
        termination: edge
      type: Route
    deploymentStrategy: Recreate
    database:
      volumeSize: 10Gi
    imagePullSecretName: redhat-pull-secret
    skipSetup: false
    registryStorage:
      persistentVolumeAccessModes:
        - ReadWriteOnce
      persistentVolumeSize: 10Gi