apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: "Red Hat OpenShift Data Foundation"
    openshift.io/display-name: "ODF"
  name: openshift-storage
  labels:
    openshift.io/cluster-monitoring: "true"